name: Build

on:
  # Run on all PRs
  pull_request:
  # Run on merge to main
  push:
    branches: [main]
  # Run when a release is published
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 1 # Fetch only the latest commit

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35

      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: Use Nix dev shell for subsequent steps
        uses: rrbutani/use-nix-shell-action@v1

      - name: Build
        run: |
          nix build \
            && mkdir -p out \
            && cp --dereference result/*.vsix out/

      - name: Upload the artifact
        uses: actions/upload-artifact@v7
        with:
          name: eyg-vscode-vsix
          path: out/

  release:
    name: Release
    runs-on: ubuntu-latest
    # Only publish when a release is published
    if: github.event_name == 'release'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 1 # Fetch only the latest commit

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35

      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: Use Nix dev shell for subsequent steps
        uses: rrbutani/use-nix-shell-action@v1

      - name: Download the artifact
        uses: actions/download-artifact@v8
        with:
          name: eyg-vscode-vsix
          path: out/

      - name: Upload artifact to release
        run: gh release upload ${{ github.ref_name }} out/*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to VSCode Marketplace
      #   run: npx --no-install --call 'vsce publish out/*.vsix'
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # - name: Publish to Open VSX
      #   run: npx --no-install --call 'ovsx publish out/*.vsix'
      #   env:
      #     OVSX_PAT: ${{ secrets.OVSX_PAT }}
