name: Build

permissions: {}

on:
  # Run on all PRs
  pull_request:
  # Run on merge to main
  push:
    branches: [main]
  # Run when a release is published
  release:
    types: [published]

jobs:
  build:
    name: Build
    permissions:
      contents: write  # For uploading to GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # ratchet:actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 1  # Fetch only the latest commit

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c  # ratchet:nixbuild/nix-quick-install-action@v35

      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # ratchet:nix-community/cache-nix-action@v7  # zizmor: ignore[cache-poisoning]
        # Don't enable the cache when releasing to avoid cache-poisoning
        if: ${{ github.event_name != 'release' }}
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: Check tag matches package version
        if: github.event_name == 'release' # Only check when a release is published
        run: scripts/check-versions-match.py "$VERSION"
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Build Nix package
        run: nix build --no-link .#eyg-vscode

      - name: Build VSIX
        run: |
          mkdir -p build/
          cat "$(nix build --no-link --print-out-paths .#eyg-vscode-vsix)" > "build/eyg-vscode-$VERSION.vsix"
        env:
          VERSION: ${{ github.event.release.tag_name }}

      - name: Upload the artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # ratchet:actions/upload-artifact@v4
        with:
          name: eyg-vscode-vsix
          path: out/

      - name: Upload VSIX file to release
        if: github.event_name == 'release' # Only upload when a release is published
        run: gh release upload "$VERSION" "out/eyg-vscode-$VERSION.vsix"
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
