name: Check

on:
  # Run on all PRs
  pull_request:
  # Run on merge to main
  push:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1  # Fetch only the latest commit
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703  # ratchet:nixbuild/nix-quick-install-action@v30
      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@c448f065ba14308da81de769632ca67a3ce67cf5  # ratchet:nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: Use Nix dev shell for subsequent steps
        uses: rrbutani/use-nix-shell-action@59a52b2b9bbfe3cc0e7deb8f9059abe37a439edf  # ratchet:rrbutani/use-nix-shell-action@v1
      - name: Run checks
        run: just check
