name: Test

on:
  # Run on all PRs
  pull_request:
  # Run on merge to main
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 1 # Fetch only the latest commit
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35
      - name: Cache Nix environment
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: Use Nix dev shell for subsequent steps
        uses: rrbutani/use-nix-shell-action@v1

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Run checks
        run: just test
